receivers:
  otlp:
    protocols:
      grpc:

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: "proto"

  # jaeger: # Corrigido o nome do exporter
  #   endpoint: "http://jaeger-all-in-one:14250" # Corrigido o endpoint
  #   insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin] # Corrigido o nome do exporter
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
