scrape_configs:
- job_name: 'otel-collector'
  scrape_interval: 5s
  static_configs:
  - targets: ['otel-collector:8888']
  - targets: ['otel-collector:8889']

- job_name: 'input'
  scrape_interval: 5s
  static_configs:
  - targets: ['microservice-input:8181']

- job_name: 'orchestration'
  scrape_interval: 5s
  static_configs:
  - targets: ['microservice-orchestration:9191']

- job_name: 'ratelimiter'
  scrape_interval: 5s
  static_configs:
  - targets: ['microservice-ratelimiter:8080']
